name: Build UserService and Test UserService
on:
  push:
    branches:
      - main
      - dev
    paths:
      - "src/services/UserService/**"
      - "tests/UserService.Tests/**" 
      - ".github/workflows/build-user-service.yml"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "src/services/UserService/**"
      - "tests/UserService.Tests/**"
      - ".github/workflows/build-user-service.yml"

env:
  PROJECT_PATH: 'src/services/UserService'
  TEST_PATH: 'tests/UserService.Tests'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v2

    - name: 'Install dotnet 6'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore Nuget packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build UserService project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: 'Run tests on UserService project and log the tests results'
      run: dotnet test ${{ env.TEST_PATH }} --logger "trx;LogFileName=test-results.trx"

    - name: 'Test Report'
      uses: dorny/test-reporter@v1
      if: success() || failure()   # run this step even if previous step failed
      with:
        name: trx Tests            # Name of the check run which will be created
        path: ${{ env.TEST_PATH }}/TestResults/test-results.trx      # Path to test results
        reporter: dotnet-trx